version: '3'
services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      HOSTNAME: 'silly.localhost'
      SERVER_NAME: 'Silly Goals'
      DATABASE_URL: "sqlite:///data/db/silly-docker-dev.db"
      REDIS_URL: "redis://:supersecretredispassword@redis:6379/0"
      RUST_BACKTRACE: 1
    volumes:
      - database:/data/db
    ports:
      - "8000:8000"
    depends_on:
      - litestream
      - redis

  redis:
    image: redis:latest
    command: redis-server --requirepass 'supersecretredispassword'

  litestream:
    image: litestream/litestream
    entrypoint: /bin/sh /usr/local/bin/litestream.sh
    volumes:
      - database:/data/db
      - ./litestream.yml:/etc/litestream.yml
      - ./litestream.sh:/usr/local/bin/litestream.sh

volumes:
  database:
