# fly.toml file generated for silly-goals on 2023-05-21T17:29:08-04:00

app = "silly-goals"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []


[env]
HOSTNAME = "silly-goals.fly.dev"
SMTP_USER = "silly-goals@mg.rickhenry.dev"
SMTP_HOST = "smtp.mailgun.org"
SMTP_PORT = "587"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8000
  protocol = "tcp"

[services.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"

[[services.ports]]
  force_https = true
  handlers = ["http"]
  port = 80

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[[services.tcp_checks]]
grace_period = "1s"
port = "8000"
interval = "15s"
restart_limit = 6
timeout = "2s"
